#!/usr/bin/env python
import optparse
import sys
import math

optparser = optparse.OptionParser()
optparser.add_option("-k", "--key", dest="key", default="data/answer_key.dev", help="Answer key (default=data/answer_key)")
(opts, _) = optparser.parse_args()

human_rank = dict([(line.split()[0],i) for i,line in enumerate(open(opts.key))])
auto_rank = dict([(line.split()[0],i) for i,line in enumerate(sys.stdin)])

if human_rank.keys() != auto_rank.keys():
  sys.stderr.write("ERROR: systems ranked in the input don't match systems ranked in answer key\n")
  sys.exit(1)

n = len(auto_rank)  
print 1 - (6*sum([math.pow(human_rank[system]-auto_rank[system],2.0) for system in human_rank]))/(n * (n*n-1))
